# ALFWorld Base Config
# From: https://github.com/alfworld/alfworld/blob/master/configs/base_config.yaml

dataset:
  data_path: '$ALFWORLD_DATA/json_2.1.1/train'
  eval_id_data_path: '$ALFWORLD_DATA/json_2.1.1/valid_seen'
  eval_ood_data_path: '$ALFWORLD_DATA/json_2.1.1/valid_unseen'
  num_train_games: -1
  num_eval_games: -1

logic:
  domain: '$ALFWORLD_DATA/logic/alfred.pddl'
  grammar: '$ALFWORLD_DATA/logic/alfred.twl2'

env:
  type: 'AlfredTWEnv'
  regen_game_files: False
  domain_randomization: False
  task_types: [1, 2, 3, 4, 5, 6]
  expert_timeout_steps: 150
  expert_type: 'handcoded'
  goal_desc_human_anns_prob: 0.0

controller:
  type: 'oracle'
  debug: False

general:
  random_seed: 42
  use_cuda: False
  training_method: 'dagger'
  save_path: './training/'
  observation_pool_capacity: 3
  hide_init_receptacles: False

